export const siteConfig = {
  name: "Erin Zhang - Software Developer",
  authorName: "Erin Zhang",
  username: "erin-zhang1",
  description:
    "Erin Zhang - Software Developer with experience building Python, R, SQL, and Django automation systems for actuarial reporting, financial data processing, and analytics.",
  url: "https://nbarkiya.xyz",
  links: {
    github: "https://github.com/erin-zhang1",
    linkedin: "https://www.linkedin.com/in/erin-zhang-823217252",
    email: "mailto:y3695zha@uwaterloo.ca",
  },
  ogImage: "/logo.png",
  iconIco: "/logo.png",
  logoIcon: "/logo.png",
  keywords: [
    "Erin Zhang",
    "Software Developer",
    "Python Developer",
    "Actuarial Software Developer",
    "Data Reporting Analyst",
    "Software Engineer",
    "Mathematical Finance",
    "Statistics",
    "Machine Learning",
    "Django",
    "SQL",
    "R",
    "ETL Pipelines",
    "Actuarial Systems",
    "Financial Data Processing",
    "Insurance Product Modeling",
    "Quantitative Trading",
    "University of Waterloo",
    "React",
    "PostgreSQL",
    "MySQL",
  ],
};
